name: Module Lint
inputs:
  icon-url:
    description: 'Url to the avatar used for the bot in Slack'
    required: false
    default: 'https://raw.githubusercontent.com/MetaMask/action-npm-publish/main/robo.png'
  username:
    description: 'The name of the bot as it appears on Slack'
    required: false
    default: 'MetaMask bot'
  subteam:
    description: 'Use this if you want to ping a subteam of individuals on Slack using @'
    required: false
  channel:
    description: 'The Slack channel to post in'
    required: false
    default: 'temp-test-module-lint'

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn --immutable

  module-lint:
    name: Module Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        projects:
          ['auto-changelog', 'create-release-branch', 'module-lint', 'utils']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --immutable --immutable-cache
      - run: yarn run-tool ${{ matrix.projects }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  slack-post:
    name: Slack Post
    runs-on: ubuntu-latest
    steps:
      - id: final-text
        shell: bash
        if: secrets.SLACK_WEBHOOK_URL != ''
        run: |
          DEFAULT_TEXT="<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/|â†’ Click here to review>"
          SUBTEAM_TEXT="${{ inputs.subteam }}"
          FINAL_TEXT="$DEFAULT_TEXT"
          if [[ ! "$SUBTEAM_TEXT" == "" ]]; then
            FINAL_TEXT="<!subteam^$SUBTEAM_TEXT> $DEFAULT_TEXT"
          fi
          echo "FINAL_TEXT=$FINAL_TEXT" >> "$GITHUB_OUTPUT"
      - name: Post module lint report to a slack
        id: slack
        if: secrets.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          payload: |
            {
              "text": "${{ steps.final-text.outputs.FINAL_TEXT }}",
              "icon_url": "${{ inputs.icon-url }}",
              "username": "${{ inputs.username }}",
              "channel": "#${{ inputs.channel }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
